# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8014d9159318be1eaf26ba5c476df7fc5ecb5e2014ee84911cf0e4824653eadca6e7d7a792743838d646fdca02f2dca8086019d4acb9e01de79d003ecfcec8eb

test:
  secret_key_base: dd21a7e0b0e9bf80e7774e623c31e78081504bbe371b060cf8d913c3f0c6b1b76dc39284bce22896b9e9e28c42d55e4b2841e3b20a078804b6b4bf072fe6727d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
