- name: article
  ingredients:
    - role: headline
      type: Text
      default: "This is a headline everybody should be able to search for."
    - role: text
      type: Richtext
      default: "This is a text block everybody should be able to search for."
    - role: image
      type: Picture

- name: secrets
  ingredients:
    - role: passwords
      type: Text
      searchable: false
      default: "This is my secret password."
    - role: confidential
      type: Richtext
      searchable: false
      default: "This is some confidential text."
    - role: image
      type: Picture
      searchable: false

- name: mixed
  ingredients:
    - role: title
      type: Text
      default: "This is my public title."
    - role: password
      type: Text
      default: "This is my secret password."
      searchable: false
    - role: public
      type: Richtext
      default: "This is some public text."
    - role: confidential
      type: Richtext
      searchable: false
      default: "This is some confidential text."
    - role: image
      type: Picture
    - role: secret_image
      type: Picture
      searchable: false

- name: searchresults
  unique: true

- name: content_test
  ingredients:
    - role: without_searchable
      type: Text
      default: "This is my public title."
    - role: with_searchable_enabled
      type: Text
      searchable: true
    - role: with_searchable_disabled
      type: Text
      searchable: false

- name: essence_test
  contents:
    - name: essence_text
      type: EssenceText
    - name: essence_richtext
      type: EssenceRichtext
    - name: essence_picture
      type: EssencePicture
  nestable_elements:
    - article

- name: ingredient_test
  ingredients:
    - role: ingredient_text
      type: Text
    - role: ingredient_richtext
      type: Richtext
    - role: ingredient_picture
      type: Picture
  nestable_elements:
    - article
