- name: intro
  unique: true

- name: standard
  elements:
  - article
  - secrets

- name: search
  searchresults: true
  unique: true
  elements:
  - searchresults
  autogenerate:
  - searchresults
